spring.application.name=hospitalmanagementjpa

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=Welcome@01

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api

spring.jpa.defer.datasource-initialization = true
spring-sql.init.mode=always
spring-sql.init.data-locations=classpth:data.sql


